name: workshop-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.2
  - pip<20.3 # https://stackoverflow.com/questions/65112585/pip-installation-stuck-in-infinite-loop-if-unresolvable-conflicts-in-dependencie
  - pip:
    - azureml-defaults
    - azureml-sdk
    - scikit-learn==0.20.3
    - pandas==0.25.3
    - joblib==0.13.2